openapi: 3.0.3
info:
  title: Bank Argent API documentation
  description: |-
    Contains all available API endpoints in this codebase
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
paths:
  /user/{accountID}:
    get:
      tags:
        - user
      summary: info of user
      description: get the user informations by his id.
      parameters:
        - in: path
          schema:
            type: number
          name: accountID
          description: The user account id
          required: true
      responses:
        '200':
          description: User's transactions retrieved successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction_Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Transaction_Response'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction_Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Transaction_Response'
  /user/{accountID}/{transactionID}:
    post:
      tags:
        - user
      summary: transaction api
      description: API for fetching details from a specific transaction
      parameters:
        - in: path
          name: accountID
          description: Account ID to return transactions
          required: true
          schema:
            type: number
        - in: path
          name : transactionID
          description: Transaction ID to return transaction details
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction_Details_Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Transaction_Details_Response'
        '401':
          description: Unauthorized
        default:
          description: successful operation
    patch:
      tags:
        - user
      summary: transaction api
      description: API for modifying transaction informations
      parameters:
        - in: path
          name: accountID
          description: Account ID to return transactions
          required: true
          schema:
            type: number
        - in: path
          name : transactionID
          description: Transaction ID to return transaction details
          required: true
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Transaction_Informations'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction_Details_Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Transaction_Details_Response'
        '401':
          description: Unauthorized
        default:
          description: successful operation
    delete:
      tags:
        - user
      summary: transaction api
      description: API for deleting transaction informations
      parameters:
        - in: path
          name: accountID
          description: Account ID to return transactions
          required: true
          schema:
            type: number
        - in: path
          name : transactionID
          description: Transaction ID to return transaction details
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Transaction informations deleted successully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delete_Response'
            application/xml:
              schema:
                $ref: '#/components/schemas/Delete_Response'
        default:
          description: successful operation
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Transaction_Response:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
                description: transaction ID
              date:
                type: string
                description: transaction date
              description:
                type: string
                description: transaction description
              amount:
                type: number
                description: transaction amount
              balance:
                type: number
                description: account balance
    Transaction_Details_Response:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            id:
              type: number
              description: transaction ID
            transactionType:
              type: string
              description: transaction type
            category:
              type: string
              description: transaction category
            notes:
              type: string
              description: transaction notes
    Transaction_Informations:
        type: object
        properties:
            transactiontype:
                type: string
                description: transaction type
            category:
                type: string
                description: transaction category
            notes:
                type: string
                description: transaction notes
    Delete_Response:
        type: object
        properties:
            status:
                type: integer
            message:
                type: string
security:
  - bearerAuth: []